### ISSUE TITLE
Homeduino in Homeassistant.

### ISSUE THREAD

**Issue by edautz** [rrooggiieerr/homeduino.py#1]
@rrooggiieerr,

I am very interested in this project.

I am have a Homeassisant and a Pimatic setup. I want the 433Mhz RF part integrated in HA reusing my Homeduino hardware. And then abandon Pimatic.

You are porting this code.

Is it working? Do you have instructions to implement it in HA? I use the docker core version of HA. And how to configure it in HA?

**Comment by rrooggiieerr** [comment]
Yes, I've got it working, only the protocols of the devices I have though. Feel free to add your protocols to the library and submit a pull request.

This is the HA integration that goes with the library:
https://github.com/rrooggiieerr/homeassistant-homeduino

The HA integration has plenty of rough edges but it's working good enough for me at the moment.

I only have one Homeduino device, need to build an other one if I want to continue developing on the code as my main Homeduino is used on my production HA
